[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = arduino
upload_protocol = dfu
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -Wl,-u,_printf_float
monitor_speed = 115200
lib_deps =
    olikraus/U8g2
